config/urls.py
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.

from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from .views import home_page_view


urlpatterns = [
    path("", view=home_page_view, name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("opentaps_seas.users.urls", namespace="users"),
    ),
    # Our Apps
    path(
        "opentaps_seas/",
        include("opentaps_seas.core.urls", namespace="core"),
    ),
    path(
        "haystack/",
        include("opentaps_seas.haystack.urls", namespace="haystack"),
    ),
    path(
        "volttron/",
        include("opentaps_seas.volttron.urls", namespace="volttron"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

if 'opentaps_seas.api.apps.ApiAppConfig' in settings.INSTALLED_APPS:
    from django.conf.urls import url
    from rest_framework_simplejwt import views as jwt_views

    urlpatterns += [
        path(
            "api/v1/",
            include("opentaps_seas.api.urls", namespace="api")
        ),

        url(r'^api/v1/token/?$', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
        url(r'^api/v1/token/refresh/?$', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    ]

opentaps_seas/api/urls.py
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.

from django.urls import path
from .views import (
    TagImportView, TagExportView
)

app_name = "api"

urlpatterns = [
    path("topic/import/<str:site_entity_id>", TagImportView.as_view(), name="topic_import"),
    path("topic/export/<str:site_entity_id>", TagExportView.as_view(), name="topic_export"),
]

opentaps_seas/core/urls.py
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.

from django.urls import path

from .views import common
from .views import entity
from .views import equipment
from .views import meter
from .views import model
from .views import point
from .views import site
from .views import tag
from .views import topic
from .views import transaction
from .views import weather
from .views import utilityapi
from .views import emissions
from .views import hyperledger

from ..eemeter.views import meter_model_calc_saving_view
from ..eemeter.views import meter_model_create_view
from ..eemeter.views import meter_model_delete_view
from ..eemeter.views import meter_model_detail_view
from ..eemeter.views import meter_model_extra_detail_view
from ..eemeter.views import meter_model_production_delete_view

app_name = "core"
urlpatterns = [
    path(
        "task_progress/json/<str:task_id>",
        view=common.get_task_progress_json,
        name="get_task_progress_json",
    ),
    path(
        "task_progress/<str:task_id>",
        view=common.get_task_progress,
        name="get_task_progress",
    ),
    path(
        "transaction/", view=transaction.transaction_list_view, name="transaction_list"
    ),
    path(
        "transaction/<str:financial_transaction_id>/",
        view=transaction.transaction_detail_view,
        name="transaction_detail",
    ),
    path(
        "transaction/edit/<path:financial_transaction_id>",
        view=transaction.transaction_edit_view,
        name="transaction_edit",
    ),
    path(
        "transaction/delete/<path:financial_transaction_id>",
        view=transaction.transaction_delete_view,
        name="transaction_delete",
    ),
    path(
        "file/transaction/<path:financial_transaction_id>",
        view=transaction.transaction_file_upload,
        name="transaction_file_upload",
    ),
    path(
        "note/transaction/<path:financial_transaction_id>",
        view=transaction.transaction_note,
        name="transaction_note",
    ),
    path(
        "link/transaction/<path:financial_transaction_id>",
        view=transaction.transaction_link,
        name="transaction_link",
    ),
    path("topic/", view=topic.topic_list_view, name="topic_list"),
    path(
        "topic_tag_rulesets/",
        view=topic.topictagruleset_list_view,
        name="topictagruleset_list",
    ),
    path(
        "topic_tag_rulesets/<str:id>",
        view=topic.topictagruleset_detail_view,
        name="topictagruleset_detail",
    ),
    path(
        "topic_tag_rulesets/op/run",
        view=topic.topictagruleset_run_view,
        name="topictagruleset_runform",
    ),
    path(
        "topic_tag_rulesets/op/run/<str:id>",
        view=topic.topictagruleset_run_view,
        name="topictagruleset_run",
    ),
    path(
        "topic_tag_rulesets/op/export",
        view=topic.topictagruleset_export_view,
        name="topictagruleset_export",
    ),
    path(
        "topic_tag_rulesets/op/import",
        view=topic.topictagruleset_import_view,
        name="topictagruleset_import",
    ),
    path(
        "newtopic_tag_ruleset/",
        view=topic.topictagruleset_create_view,
        name="topictagruleset_create",
    ),
    path(
        "topic_tag_rule/<str:id>",
        view=topic.topic_list_view,
        name="topictagrule_detail",
    ),
    path(
        "topic_tag_rule/op/run/<str:id>",
        view=topic.topictagrule_run_view,
        name="topictagrule_run",
    ),
    path(
        "newtopic_tag_rule/<str:id>",
        view=topic.topictagrule_create_view,
        name="topictagrule_forset_create",
    ),
    path(
        "newtopic_tag_rule/",
        view=topic.topictagrule_create_view,
        name="topictagrule_create",
    ),
    path("tag_topics/", view=topic.tag_topics, name="tag_topics"),
    path("topic_table/", view=topic.topic_list_table, name="topic_table"),
    path(
        "topic_table_fields/",
        view=topic.topic_list_table_fields,
        name="topic_table_fields",
    ),
    path("topic_json/", view=topic.topic_list_json, name="topic_json"),
    path("topic_rules/", view=topic.topic_rules, name="topic_rules"),
    path("topic/import", view=topic.topic_import_view, name="topic_import"),
    path("topic/export", view=topic.topic_export_view, name="topic_export0"),
    path("topic/export/<str:site>", view=topic.topic_export_view, name="topic_export"),
    path("topic/setup/<path:topic>", view=topic.topic_setup_view, name="topic_setup"),
    path("topic/assoc/<path:topic>", view=topic.topic_assoc, name="topic_assoc"),
    path(
        "topic/csv/report_tags",
        view=topic.topic_report_tags_csv,
        name="topic_report_tags_csv",
    ),
    path("entity/", view=entity.entity_list_view, name="entity_list"),
    path(
        "entity/<path:entity_id>", view=entity.entity_detail_view, name="entity_detail"
    ),
    path(
        "file/entity/<path:entity_id>",
        view=entity.entity_file_upload,
        name="entity_file_upload",
    ),
    path("link/entity/<path:entity_id>", view=entity.entity_link, name="entity_link"),
    path("note/entity/<path:entity_id>", view=entity.entity_note, name="entity_note"),
    path("tag/entity/<path:entity_id>", view=entity.entity_tag, name="entity_tag"),
    path("tag/", view=tag.tag_list_view, name="tag_list"),
    path("tag.json", view=tag.tag_list_json_view, name="tag_list_json"),
    path("newtag/", view=tag.tag_create_view, name="tag_create"),
    path("tag/edit/<path:tag>", view=tag.tag_edit_view, name="tag_edit"),
    path("tag/delete/<path:tag>", view=tag.tag_delete_view, name="tag_delete"),
    path("tag/view/<path:tag>", view=tag.tag_detail_view, name="tag_detail"),
    path("tag/import", view=tag.tag_import_view, name="tag_import"),
    path(
        "hyperledger/",
        view=hyperledger.hyperledger_query_admin_view,
        name="hyperledger_query_admin",
    ),
    path(
        "hyperledger/success/<str:name>/<str:exists>",
        view=hyperledger.hyperledger_query_admin_success_view,
        name="hyperledger_query_admin_success",
    ),
    path(
        "hyperledger/enroll/<str:org_name>/<str:user>",
        view=hyperledger.hyperledger_enroll_view,
        name="hyperledger_enroll",
    ),
    path(
        "hyperledger/enroll/result/<str:user>/<str:org_name>/<str:result>",
        view=hyperledger.hyperledger_enroll_result_view,
        name="hyperledger_enroll_result",
    ),
    path("model/", view=model.model_list_view, name="model_list"),
    path("model.json", view=model.model_list_json_view, name="model_list_json"),
    path("meter.json", view=meter.meter_list_json_view, name="meter_list_json"),
    path("newmeter/<str:site_id>", view=meter.meter_create_view, name="meter_create"),
    path(
        "meter_rate_plan/<str:rate_plan_id>",
        view=meter.meter_rate_plan_detail_view,
        name="meter_rate_plan_detail",
    ),
    path(
        "meter_rate_plan_history/<path:meter_id>",
        view=meter.meter_rate_plan_history_view,
        name="meter_rate_plan_history",
    ),
    path("meter/edit/<path:meter_id>", view=meter.meter_edit_view, name="meter_edit"),
    path(
        "meter/deactivate/<path:meter_id>",
        view=meter.meter_deactivate_view,
        name="meter_deactivate",
    ),
    path(
        "meter/view/<path:meter_id>", view=meter.meter_detail_view, name="meter_detail"
    ),
    path("meter/json/<str:meter>", view=meter.meter_data_json, name="meter_data_json"),
    path(
        "meter/<str:meter>/financial_values_table",
        view=meter.meter_financial_values_table,
        name="meter_financial_values_table",
    ),
    path(
        "meter/<str:meter>/financial_values/<str:meter_value_id>",
        view=meter.meter_financial_value_detail,
        name="meter_financial_value_detail",
    ),
    path(
        "meter/<str:meter>/transactions_table",
        view=transaction.meter_transactions_table,
        name="meter_transactions_table",
    ),
    path(
        "meter_financial_value_items_table/<str:meter_value_id>",
        view=meter.meter_financial_value_items_table,
        name="meter_financial_value_items_table",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>",
        view=meter_model_detail_view,
        name="meter_model_detail",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>/details",
        view=meter_model_extra_detail_view,
        name="meter_model_extra_detail",
    ),
    path(
        "meter/<str:meter_id>/create/model",
        view=meter_model_create_view,
        name="meter_model_create",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>/delete",
        view=meter_model_delete_view,
        name="meter_model_delete",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>/delete_production",
        view=meter_model_production_delete_view,
        name="meter_model_production_delete",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>/calc_saving",
        view=meter_model_calc_saving_view,
        name="meter_model_calc_saving",
    ),
    path("newmodel/", view=model.model_create_view, name="model_create"),
    path(
        "newmodel/<path:entity_id>",
        view=model.model_create_view,

opentaps_seas/users/urls.py
from django.urls import path

from opentaps_seas.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

opentaps_seas/core/forms/entity.py
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.

import logging
from ..models import EntityFile
from ..models import EntityNote
from django import forms

logger = logging.getLogger(__name__)


class EntityFileUploadForm(forms.ModelForm):

    class Meta:
        model = EntityFile
        fields = ["id", "entity_id", "comments", "owner", "uploaded_file"]


class EntityNoteForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea, required=True)

    class Meta:
        model = EntityNote
        fields = ["id", "entity_id", "content", "owner"]


class EntityNoteUpdateForm(forms.Form):
    id = forms.IntegerField()
    entity_id = forms.CharField(max_length=255)
    content = forms.CharField(widget=forms.Textarea, required=True)


class EntityNoteDeleteForm(forms.Form):
    id = forms.IntegerField()
    entity_id = forms.CharField(max_length=255)


class EntityLinkForm(forms.ModelForm):
    entity_id = forms.CharField(max_length=255)
    comments = forms.CharField(widget=forms.Textarea, required=False)
    link = forms.URLField()
    link_name = forms.CharField()

    class Meta:
        model = EntityFile
        fields = ["id", "entity_id", "comments", "owner", "link", "link_name"]

opentaps_seas/core/forms/hyperledger.py
from django import forms


class HyperLedgerQueryAdminForm(forms.Form):
    name = forms.CharField(label="Org Name:")

    class Meta:
        fields = ["name"]


class HyperLedgerEnrollUserForm(forms.Form):
    affiliation = forms.CharField()

    class Meta:
        fields = ["affiliation"]

opentaps_seas/templates/core/hyperledger_query_admin_success.html
{% extends "base.html" %}
{% comment 'header' %}
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>. {% endcomment %} {% load crispy_forms_tags %} {% block content %} <div
  class="content-section">
  {% if exists == "existing" %}
  <h2>Enroll User</h2>
  {% else %}
  <h2>Enroll User</h2>
  <p class="alert alert-success">Successfully registered new organization {{name}}.</p>
  {% endif %}
  <ul class="pt-3">
    {% for user in all_users %}
    {% if user.org_name != name%}

    <li>
      <a href="{% url 'core:hyperledger_enroll' user=user org_name=name%}">
        <input type="submit" value={{user}} name="mybtn" id="start_submit" class="d-block"
          style="border: none; background-color: white; color: blue;" />
      </a>
    </li>
    {% endif %}
    {% endfor %}
  </ul>
  <p class="pt-5 font-weight-bold">Users currently enrolled in {{name}}</p>
  <ul>
    {% for user in all_users %}
    {% if user.org_name == name %}
    <li>
      <p class="d-block ml-1">{{user}}</p>
    </li>
    {% endif %}
    {% endfor %}
  </ul>
  <br><a href="{% url 'core:hyperledger_query_admin' %}">
    <button class="btn btn-primary mt-5" type="submit">Back</button>
  </a>
  </div>
  {% endblock %}

opentaps_seas/templates/core/model_list.html
{% extends "base.html" %}
{% comment 'header' %}
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% load static i18n %}
{% block title %}Models{% endblock %}

{% block content %}
<div class="container">

  {% include "core/_breadcrumbs.html" %}

  <div class="card mb-3">
    <div class="card-body">
      {% load render_table from django_tables2 %}
      {% url 'core:model_create' as model_create_url %}
      {% include "core/_table_filter_add.html" with add_label='Add Model' add_url=model_create_url %}
      {% render_table table %}
    </div>
  </div>
</div>
{% endblock content %}

opentaps_seas/templates/core/site_detail.html
{% extends "base.html" %}
{% comment 'header' %}
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% load static %}
{% load time_str from core_tags %}
{% load fmttime_str from core_tags %}

{% block title %}Site: {{ object.entity_id }}{% endblock %}

{% block content %}
<div class="container">

  {% include "core/_breadcrumbs.html" %}

  <div class="card mb-3">
    <div class="card-body">
      {% if tags_form %}
        {% include "core/_tags.html" with form_title='Add Tag' nodecor=True section_tag='h2' section_title=object.description section_subtitle_name='Entity id:' section_subtitle=object.entity_id form=tags_form items=tags head_tags=head_tags %}
        {% if head_tags %}
          {% include "core/_head_tags.html" with form=tags_form items=head_tags %}
        {% endif %}
      {% else %}
        <h2>Site {{ object.description }}</h2>
      {% endif %}
    </div>
  </div>

  {% include "core/_site_chart.html" with site_id=object.entity_id %}

  {% load render_table from django_tables2 %}

  <div class="card mb-3">
    <div class="card-body">
      <h3>
        <div class="row m-0">
          <div class="">
            Meters
          </div>
          <div class="text-right flex-grow-1">
            <a class="btn btn-primary" href="{% url 'core:meter_create' object.entity_id %}"><i class="fa fa-plus"></i> Add Meter</a>
          </div>
        </div>
      </h3>
      <div class="container header-top">
          {% for meter in meters %}
            <h6 class="meter-row">
                <div class="container">
                    <div class="row">
                      <div class="col-4">
                        <div><a href="{% url 'core:meter_detail' meter.meter_id %}">{{ meter.meter_id }}</a></div>
                      </div>
                      <div class="col-4">
                        {{ meter.description }}
                      </div>
                      <div class="col-4">
                        {% if meter.latest_reading %}
                          <b>{{ meter.latest_reading.value }} {{ meter.latest_reading.uom.unit }}</b>
                          as of
                          <my-datetime value="{{ meter.latest_reading.as_of_datetime|time_str }}">{{ meter.latest_reading.as_of_datetime|fmttime_str }}</my-datetime>
                        {% endif %}
                      </div>
                    </div>
                </div>
            </h6>
          {% endfor %}
      </div>
    </div>
  </div>

  <div id="datetimelist">
    <div class="card mb-3">
      <div class="card-body">
        <h3>
          <div class="row m-0">
            <div class="">
              Equipment
            </div>
            <div class="text-right flex-grow-1">
              <a class="btn btn-primary" href="{{ link_add_url }}"><i class="fa fa-plus"></i> Add Equipment</a>
            </div>
          </div>
        </h3>
        <div class="container header-top">
        {% for e in equipments %}
            <h5 class="card-title"></h5>

            <h6 class="equip-row position-relative" >
              <b-container>
                <b-row class="text-left">
                  <b-col cols="9">
                    <a href="{% url 'core:site_equipment_detail' e.site.entity_id e.equipment.entity_id  %}">{{ e.equipment.description }}</a>
                  </b-col>
                  <b-col cols="2">
                    <div class="a-rt">{{ e.data_points }} Data Points</div>
                  </b-col>
                  <b-col class="text-right chev-btn" v-b-toggle.collapse_datapoints{{ forloop.counter }}>
                    <b-button variant="light" size="sm" class="a-rt when-opened">
                       <i class="fa fa-chevron-up"></i>
                    </b-button>
                    <b-button variant="light" size="sm" class="a-rt when-closed">
                       <i class="fa fa-chevron-down"></i>
                    </b-button>
                  </b-col>
                </b-row>
              </b-container>
            </h6>

            <b-collapse v-cloak id="collapse_datapoints{{ forloop.counter }}" v-on:show="show_collapse('collapse_datapoints{{ forloop.counter }}', '{{e.equipment.entity_id}}')">
              <p>Loading ...</p>
            </b-collapse>

        {% endfor %}
        </div>
      </div>
    </div>
  </div>

  {% if has_transactions %}
    {% url 'core:site_transactions_table' object.entity_id as site_transactions_url %}
    {% include "core/_ajax_table.html" with title="Transactions" name="transactions" table_url=site_transactions_url %}
  {% endif %}

  {% if file_upload_form %}
    {% include "core/_upload.html" with form_title='Upload File' link_form_title='Add Link' form=file_upload_form items=files %}
  {% endif %}

  {% if notes_form %}
    {% include "core/_notes.html" with form_title='Add Note' form=notes_form items=notes %}
  {% endif %}

  {% if bacnet_configs %}
  <div class="card mb-3">
    <div class="card-body">
      <h3>
        <div class="row m-0">
          <div class="">
            BACNet Configs
          </div>
          <div class="text-right flex-grow-1">
            <form method="POST" action="{% url 'core:topic_list' %}">
              {% csrf_token %}
              <input type="hidden" name="site" value="{{ object.object_id }}"/>
              <button class="btn btn-info " type="submit">Topics</button>
              <a class="btn btn-info" href="{% url 'core:topic_export' object.entity_id %}"><i class="fa fa-download"></i> Export</a>
            </form>
          </div>
        </div>
      </h3>
      <div class="header-top">
          {% for bc in bacnet_configs %}
            <h6 class="bacnet-row" >
              <div class="row">
                <div class="col-3">
                  <div>{{ bc.prefix }}</div>
                </div>
                <div class="col-3">
                {% if bc.bc_equipment_entity_id %}
                    <a href="{% url 'core:site_equipment_detail' object.entity_id bc.bc_equipment_entity_id  %}">{{ bc.bc_equipment_description }}</a>
                {% else %}
                  <a class="btn btn-primary" href="{{ link_add_url }}?bacnet_prefix={{ bc.prefix }}&device_id={{ bc.device_id }}"><i class="fa fa-plus"></i> Add Equipment</a>
                {% endif %}
                </div>
                <div class="col-6 text-right">
                  <form method="POST" action="{% url 'core:topic_list' %}">
                    {% csrf_token %}
                    <input type="hidden" name="bacnet_prefix" value="{{ bc.prefix }}"/>
                    <input type="hidden" name="site" value="{{ object.object_id }}"/>
                    <button class="btn btn-info" type="submit">Topics</button>
                    <a class="btn btn-info" href="{% url 'core:topic_export' object.entity_id %}?bacnet_prefix={{ bc.prefix }}"><i class="fa fa-download"></i> Export</a>
                    <a class="btn btn-info" href="{% url 'core:topictagruleset_runform' %}?topic_filter={{ bc.prefix }}"><i class="fa fa-cog mr-2"></i>Run Rules</a>
                  </form>
                </div>
              </div>
            </h6>
          {% endfor %}
      </div>
    </div>
  </div>
  {% endif %}

</div>
<script>
(function(){
  new Vue({
    delimiters: ['${', '}'],
    el: '#datetimelist',
    methods: {
      show_collapse(container_id, equipment_id) {
        container = document.getElementById(container_id)
        container.innerHTML = '<p>Loading ...</p>'
        url = dutils.urls.resolve('equipment_data_points_table', { id: equipment_id })
        axios.get(url).then(response => {
          container.innerHTML = response.data
        });
      }
    }
  });
})();
</script>
{% endblock content %}