config/urls.py
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.

from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from .views import home_page_view


urlpatterns = [
    path("", view=home_page_view, name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("opentaps_seas.users.urls", namespace="users"),
    ),
    # Our Apps
    path(
        "opentaps_seas/",
        include("opentaps_seas.core.urls", namespace="core"),
    ),
    path(
        "haystack/",
        include("opentaps_seas.haystack.urls", namespace="haystack"),
    ),
    path(
        "volttron/",
        include("opentaps_seas.volttron.urls", namespace="volttron"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

if 'opentaps_seas.api.apps.ApiAppConfig' in settings.INSTALLED_APPS:
    from django.conf.urls import url
    from rest_framework_simplejwt import views as jwt_views

    urlpatterns += [
        path(
            "api/v1/",
            include("opentaps_seas.api.urls", namespace="api")
        ),

        url(r'^api/v1/token/?$', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
        url(r'^api/v1/token/refresh/?$', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    ]

opentaps_seas/api/urls.py
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.

from django.urls import path
from .views import (
    TagImportView, TagExportView
)

app_name = "api"

urlpatterns = [
    path("topic/import/<str:site_entity_id>", TagImportView.as_view(), name="topic_import"),
    path("topic/export/<str:site_entity_id>", TagExportView.as_view(), name="topic_export"),
]

opentaps_seas/core/urls.py
        "topic_tag_rulesets/op/export",
        view=topic.topictagruleset_export_view,
        name="topictagruleset_export",
    ),
    path(
        "topic_tag_rulesets/op/import",
        view=topic.topictagruleset_import_view,
        name="topictagruleset_import",
    ),
    path(
        "newtopic_tag_ruleset/",
        view=topic.topictagruleset_create_view,
        name="topictagruleset_create",
    ),
    path(
        "topic_tag_rule/<str:id>",
        view=topic.topic_list_view,
        name="topictagrule_detail",
    ),
    path(
        "topic_tag_rule/op/run/<str:id>",
        view=topic.topictagrule_run_view,
        name="topictagrule_run",
    ),
    path(
        "newtopic_tag_rule/<str:id>",
        view=topic.topictagrule_create_view,
        name="topictagrule_forset_create",
    ),
    path(
        "newtopic_tag_rule/",
        view=topic.topictagrule_create_view,
        name="topictagrule_create",
    ),
    path("tag_topics/", view=topic.tag_topics, name="tag_topics"),
    path("topic_table/", view=topic.topic_list_table, name="topic_table"),
    path(
        "topic_table_fields/",
        view=topic.topic_list_table_fields,
        name="topic_table_fields",
    ),
    path("topic_json/", view=topic.topic_list_json, name="topic_json"),
    path("topic_rules/", view=topic.topic_rules, name="topic_rules"),
    path("topic/import", view=topic.topic_import_view, name="topic_import"),
    path("topic/export", view=topic.topic_export_view, name="topic_export0"),
    path("topic/export/<str:site>", view=topic.topic_export_view, name="topic_export"),
    path("topic/setup/<path:topic>", view=topic.topic_setup_view, name="topic_setup"),
    path("topic/assoc/<path:topic>", view=topic.topic_assoc, name="topic_assoc"),
    path(
        "topic/csv/report_tags",
        view=topic.topic_report_tags_csv,
        name="topic_report_tags_csv",
    ),
    path("entity/", view=entity.entity_list_view, name="entity_list"),
    path(
        "entity/<path:entity_id>", view=entity.entity_detail_view, name="entity_detail"
    ),
    path(
        "file/entity/<path:entity_id>",
        view=entity.entity_file_upload,
        name="entity_file_upload",
    ),
    path("link/entity/<path:entity_id>", view=entity.entity_link, name="entity_link"),
    path("note/entity/<path:entity_id>", view=entity.entity_note, name="entity_note"),
    path("tag/entity/<path:entity_id>", view=entity.entity_tag, name="entity_tag"),
    path("tag/", view=tag.tag_list_view, name="tag_list"),
    path("tag.json", view=tag.tag_list_json_view, name="tag_list_json"),
    path("newtag/", view=tag.tag_create_view, name="tag_create"),
    path("tag/edit/<path:tag>", view=tag.tag_edit_view, name="tag_edit"),
    path("tag/delete/<path:tag>", view=tag.tag_delete_view, name="tag_delete"),
    path("tag/view/<path:tag>", view=tag.tag_detail_view, name="tag_detail"),
    path("tag/import", view=tag.tag_import_view, name="tag_import"),
    path(
        "hyperledger/",
        view=hyperledger.hyperledger_query_admin_view,
        name="hyperledger_query_admin",
    ),
    path(
        "hyperledger/success/<str:name>/<str:exists>",
        view=hyperledger.hyperledger_query_admin_success_view,
        name="hyperledger_query_admin_success",
    ),
    path(
        "hyperledger/enroll/<str:org_name>/<str:user>",
        view=hyperledger.hyperledger_enroll_view,
        name="hyperledger_enroll",
    ),
    path(
        "hyperledger/enroll/result/<str:user>/<str:org_name>/<str:result>",
        view=hyperledger.hyperledger_enroll_result_view,
        name="hyperledger_enroll_result",
    ),
    path("model/", view=model.model_list_view, name="model_list"),
    path("model.json", view=model.model_list_json_view, name="model_list_json"),
    path("meter.json", view=meter.meter_list_json_view, name="meter_list_json"),
    path("newmeter/<str:site_id>", view=meter.meter_create_view, name="meter_create"),
    path(
        "meter_rate_plan/<str:rate_plan_id>",
        view=meter.meter_rate_plan_detail_view,
        name="meter_rate_plan_detail",
    ),
    path(
        "meter_rate_plan_history/<path:meter_id>",
        view=meter.meter_rate_plan_history_view,
        name="meter_rate_plan_history",
    ),
    path("meter/edit/<path:meter_id>", view=meter.meter_edit_view, name="meter_edit"),
    path(
        "meter/deactivate/<path:meter_id>",
        view=meter.meter_deactivate_view,
        name="meter_deactivate",
    ),
    path(
        "meter/view/<path:meter_id>", view=meter.meter_detail_view, name="meter_detail"
    ),
    path("meter/json/<str:meter>", view=meter.meter_data_json, name="meter_data_json"),
    path(
        "meter/<str:meter>/financial_values_table",
        view=meter.meter_financial_values_table,
        name="meter_financial_values_table",
    ),
    path(
        "meter/<str:meter>/financial_values/<str:meter_value_id>",
        view=meter.meter_financial_value_detail,
        name="meter_financial_value_detail",
    ),
    path(
        "meter/<str:meter>/transactions_table",
        view=transaction.meter_transactions_table,
        name="meter_transactions_table",
    ),
    path(
        "meter_financial_value_items_table/<str:meter_value_id>",
        view=meter.meter_financial_value_items_table,
        name="meter_financial_value_items_table",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>",
        view=meter_model_detail_view,
        name="meter_model_detail",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>/details",
        view=meter_model_extra_detail_view,
        name="meter_model_extra_detail",
    ),
    path(
        "meter/<str:meter_id>/create/model",
        view=meter_model_create_view,
        name="meter_model_create",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>/delete",
        view=meter_model_delete_view,
        name="meter_model_delete",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>/delete_production",
        view=meter_model_production_delete_view,
        name="meter_model_production_delete",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>/calc_saving",
        view=meter_model_calc_saving_view,
        name="meter_model_calc_saving",
    ),
    path("newmodel/", view=model.model_create_view, name="model_create"),
    path(
        "newmodel/<path:entity_id>",
        view=model.model_create_view,
        name="model_create_for",
    ),
    path(
        "dupmodel/<path:entity_id>",
        view=model.model_duplicate_view,
        name="model_duplicate",
    ),
    path("newsite/", view=site.site_create_view, name="site_create"),
    path("model/edit/<path:entity_id>", view=model.model_edit_view, name="model_edit"),
    path(
        "model/delete/<path:entity_id>",
        view=model.model_delete_view,
        name="model_delete",
    ),
    path(
        "model/view/<path:entity_id>", view=model.model_detail_view, name="model_detail"
    ),
    path(
        "equipment.json",
        view=equipment.equipment_list_json_view,
        name="equipment_list_json",
    ),
    path("equipment/", view=equipment.equipment_list_view, name="equipment_list"),
    path(
        "equipment/<path:equip>",
        view=equipment.equipment_detail_view,
        name="equipment_detail",
    ),
    path(
        "equipment_dashboard/<path:equip>",
        view=equipment.equipment_dashboard,
        name="equipment_dashboard",
    ),
    path(
        "equipment_fetch_solaredge_details/<path:equip>",
        view=equipment.equipment_fetch_solaredge_details,
        name="equipment_fetch_solaredge_details",
    ),
    path(
        "equipment_solaredge_edit/<path:equip>",
        view=equipment.equipment_solaredge_edit_view,
        name="equipment_solaredge_edit_view",
    ),
    path(
        "equipment_points_table/<path:equip>",
        view=equipment.equipment_data_points_table,
        name="equipment_data_points_table",
    ),
    path(
        "site/<str:site>/newequipment/",
        view=equipment.equipment_create_view,
        name="equipment_create",
    ),
    path("", view=site.site_list_view, name="site_list_default"),
    path("site/", view=site.site_list_view, name="site_list"),
    path("site.json", view=site.site_list_json_view, name="site_list_json"),
    path("site/<str:site>/", view=site.site_detail_view, name="site_detail"),
    path(
        "site/<str:site>/pie_chart.json",
        view=site.site_pie_chart_data_json,
        name="site_pie_chart_data_json",
    ),
    path(
        "site/<str:site>/ahu_summary.json",
        view=site.site_ahu_summary_json,
        name="site_ahu_summary_json",
    ),
    path(
        "site/<str:site>/transactions_table",
        view=transaction.site_transactions_table,
        name="site_transactions_table",
    ),
    path(
        "site/<str:site>/equipment/<str:equip>/",
        view=equipment.equipment_site_detail_view,
        name="site_equipment_detail",
    ),
    path(
        "site/<str:site>/equipment/<str:equip>/csv/<path:point>",
        view=point.point_data_csv,
        name="site_equipment_point_data_csv",
    ),
    path(
        "site/<str:site>/equipment/<str:equip>/json/<path:point>",
        view=point.point_data_json,
        name="site_equipment_point_data_json",
    ),
    path(
        "site/<str:site>/equipment/<str:equip>/<path:point>",
        view=equipment.equipment_point_detail_view,
        name="site_equipment_point_detail",
    ),
    path("point/csv/<path:point>", view=point.point_data_csv, name="point_data_csv"),
    path("point/json/<path:point>", view=point.point_data_json, name="point_data_json"),
    path("point/<path:entity_id>", view=point.point_detail_view, name="point_detail"),
    path(
        "state.json/<str:country>",
        view=common.state_list_json_view,
        name="state_list_json",
    ),
    path(
        "timezone.json/<str:geo_id>",
        view=common.timezone_list_json_view,

opentaps_seas/users/urls.py
from django.urls import path

from opentaps_seas.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

opentaps_seas/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)
    org_name = CharField(_("User's Organization"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

opentaps_seas/core/forms/entity.py
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.

import logging
from ..models import EntityFile
from ..models import EntityNote
from django import forms

logger = logging.getLogger(__name__)


class EntityFileUploadForm(forms.ModelForm):

    class Meta:
        model = EntityFile
        fields = ["id", "entity_id", "comments", "owner", "uploaded_file"]


class EntityNoteForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea, required=True)

    class Meta:
        model = EntityNote
        fields = ["id", "entity_id", "content", "owner"]


class EntityNoteUpdateForm(forms.Form):
    id = forms.IntegerField()
    entity_id = forms.CharField(max_length=255)
    content = forms.CharField(widget=forms.Textarea, required=True)


class EntityNoteDeleteForm(forms.Form):
    id = forms.IntegerField()
    entity_id = forms.CharField(max_length=255)


class EntityLinkForm(forms.ModelForm):
    entity_id = forms.CharField(max_length=255)
    comments = forms.CharField(widget=forms.Textarea, required=False)
    link = forms.URLField()
    link_name = forms.CharField()

    class Meta:
        model = EntityFile
        fields = ["id", "entity_id", "comments", "owner", "link", "link_name"]

opentaps_seas/core/forms/hyperledger.py
from django import forms


class HyperLedgerQueryAdminForm(forms.Form):
    name = forms.CharField(label="Org Name:")

    class Meta:
        fields = ["name"]


class HyperLedgerEnrollUserForm(forms.Form):
    affiliation = forms.CharField()

    class Meta:
        fields = ["affiliation"]

opentaps_seas/templates/users/user_detail.html
{% extends "base.html" %}
{% comment 'header' %}
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% load static %}
{% load static i18n %}
{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

   <div class="col-sm-12">
      <br/><br/>
      <a class="btn btn-danger" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
   </div>

<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

opentaps_seas/templates/users/user_form.html
{% extends "base.html" %}
{% comment 'header' %}
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

opentaps_seas/templates/users/user_list.html
{% extends "base.html" %}
{% comment 'header' %}
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}