config/urls.py
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.

from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from .views import home_page_view


urlpatterns = [
    path("", view=home_page_view, name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("opentaps_seas.users.urls", namespace="users"),
    ),
    # Our Apps
    path(
        "opentaps_seas/",
        include("opentaps_seas.core.urls", namespace="core"),
    ),
    path(
        "haystack/",
        include("opentaps_seas.haystack.urls", namespace="haystack"),
    ),
    path(
        "volttron/",
        include("opentaps_seas.volttron.urls", namespace="volttron"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

if 'opentaps_seas.api.apps.ApiAppConfig' in settings.INSTALLED_APPS:
    from django.conf.urls import url
    from rest_framework_simplejwt import views as jwt_views

    urlpatterns += [
        path(
            "api/v1/",
            include("opentaps_seas.api.urls", namespace="api")
        ),

        url(r'^api/v1/token/?$', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
        url(r'^api/v1/token/refresh/?$', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    ]

opentaps_seas/api/urls.py
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.

from django.urls import path
from .views import (
    TagImportView, TagExportView
)

app_name = "api"

urlpatterns = [
    path("topic/import/<str:site_entity_id>", TagImportView.as_view(), name="topic_import"),
    path("topic/export/<str:site_entity_id>", TagExportView.as_view(), name="topic_export"),
]

opentaps_seas/core/urls.py
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.

from django.urls import path

from .views import common
from .views import entity
from .views import equipment
from .views import meter
from .views import model
from .views import point
from .views import site
from .views import tag
from .views import topic
from .views import transaction
from .views import weather
from .views import utilityapi
from .views import emissions
from .views import hyperledger

from ..eemeter.views import meter_model_calc_saving_view
from ..eemeter.views import meter_model_create_view
from ..eemeter.views import meter_model_delete_view
from ..eemeter.views import meter_model_detail_view
from ..eemeter.views import meter_model_extra_detail_view
from ..eemeter.views import meter_model_production_delete_view

app_name = "core"
urlpatterns = [
    path(
        "task_progress/json/<str:task_id>",
        view=common.get_task_progress_json,
        name="get_task_progress_json",
    ),
    path(
        "task_progress/<str:task_id>",
        view=common.get_task_progress,
        name="get_task_progress",
    ),
    path(
        "transaction/", view=transaction.transaction_list_view, name="transaction_list"
    ),
    path(
        "transaction/<str:financial_transaction_id>/",
        view=transaction.transaction_detail_view,
        name="transaction_detail",
    ),
    path(
        "transaction/edit/<path:financial_transaction_id>",
        view=transaction.transaction_edit_view,
        name="transaction_edit",
    ),
    path(
        "transaction/delete/<path:financial_transaction_id>",
        view=transaction.transaction_delete_view,
        name="transaction_delete",
    ),
    path(
        "file/transaction/<path:financial_transaction_id>",
        view=transaction.transaction_file_upload,
        name="transaction_file_upload",
    ),
    path(
        "note/transaction/<path:financial_transaction_id>",
        view=transaction.transaction_note,
        name="transaction_note",
    ),
    path(
        "link/transaction/<path:financial_transaction_id>",
        view=transaction.transaction_link,
        name="transaction_link",
    ),
    path("topic/", view=topic.topic_list_view, name="topic_list"),
    path(
        "topic_tag_rulesets/",
        view=topic.topictagruleset_list_view,
        name="topictagruleset_list",
    ),
    path(
        "topic_tag_rulesets/<str:id>",
        view=topic.topictagruleset_detail_view,
        name="topictagruleset_detail",
    ),
    path(
        "topic_tag_rulesets/op/run",
        view=topic.topictagruleset_run_view,
        name="topictagruleset_runform",
    ),
    path(
        "topic_tag_rulesets/op/run/<str:id>",
        view=topic.topictagruleset_run_view,
        name="topictagruleset_run",
    ),
    path(
        "topic_tag_rulesets/op/export",
        view=topic.topictagruleset_export_view,
        name="topictagruleset_export",
    ),
    path(
        "topic_tag_rulesets/op/import",
        view=topic.topictagruleset_import_view,
        name="topictagruleset_import",
    ),
    path(
        "newtopic_tag_ruleset/",
        view=topic.topictagruleset_create_view,
        name="topictagruleset_create",
    ),
    path(
        "topic_tag_rule/<str:id>",
        view=topic.topic_list_view,
        name="topictagrule_detail",
    ),
    path(
        "topic_tag_rule/op/run/<str:id>",
        view=topic.topictagrule_run_view,
        name="topictagrule_run",
    ),
    path(
        "newtopic_tag_rule/<str:id>",
        view=topic.topictagrule_create_view,
        name="topictagrule_forset_create",
    ),
    path(
        "newtopic_tag_rule/",
        view=topic.topictagrule_create_view,
        name="topictagrule_create",
    ),
    path("tag_topics/", view=topic.tag_topics, name="tag_topics"),
    path("topic_table/", view=topic.topic_list_table, name="topic_table"),
    path(
        "topic_table_fields/",
        view=topic.topic_list_table_fields,
        name="topic_table_fields",
    ),
    path("topic_json/", view=topic.topic_list_json, name="topic_json"),
    path("topic_rules/", view=topic.topic_rules, name="topic_rules"),
    path("topic/import", view=topic.topic_import_view, name="topic_import"),
    path("topic/export", view=topic.topic_export_view, name="topic_export0"),
    path("topic/export/<str:site>", view=topic.topic_export_view, name="topic_export"),
    path("topic/setup/<path:topic>", view=topic.topic_setup_view, name="topic_setup"),
    path("topic/assoc/<path:topic>", view=topic.topic_assoc, name="topic_assoc"),
    path(
        "topic/csv/report_tags",
        view=topic.topic_report_tags_csv,
        name="topic_report_tags_csv",
    ),
    path("entity/", view=entity.entity_list_view, name="entity_list"),
    path(
        "entity/<path:entity_id>", view=entity.entity_detail_view, name="entity_detail"
    ),
    path(
        "file/entity/<path:entity_id>",
        view=entity.entity_file_upload,
        name="entity_file_upload",
    ),
    path("link/entity/<path:entity_id>", view=entity.entity_link, name="entity_link"),
    path("note/entity/<path:entity_id>", view=entity.entity_note, name="entity_note"),
    path("tag/entity/<path:entity_id>", view=entity.entity_tag, name="entity_tag"),
    path("tag/", view=tag.tag_list_view, name="tag_list"),
    path("tag.json", view=tag.tag_list_json_view, name="tag_list_json"),
    path("newtag/", view=tag.tag_create_view, name="tag_create"),
    path("tag/edit/<path:tag>", view=tag.tag_edit_view, name="tag_edit"),
    path("tag/delete/<path:tag>", view=tag.tag_delete_view, name="tag_delete"),
    path("tag/view/<path:tag>", view=tag.tag_detail_view, name="tag_detail"),
    path("tag/import", view=tag.tag_import_view, name="tag_import"),
    path(
        "hyperledger/",
        view=hyperledger.hyperledger_query_admin_view,
        name="hyperledger_query_admin",
    ),
    path(
        "hyperledger/success/<str:name>/<str:exists>",
        view=hyperledger.hyperledger_query_admin_success_view,
        name="hyperledger_query_admin_success",
    ),
    path(
        "hyperledger/enroll/<str:org_name>/<str:user>",
        view=hyperledger.hyperledger_enroll_view,
        name="hyperledger_enroll",
    ),
    path(
        "hyperledger/enroll/result/<str:user>/<str:org_name>/<str:result>",
        view=hyperledger.hyperledger_enroll_result_view,
        name="hyperledger_enroll_result",
    ),
    path("model/", view=model.model_list_view, name="model_list"),
    path("model.json", view=model.model_list_json_view, name="model_list_json"),
    path("meter.json", view=meter.meter_list_json_view, name="meter_list_json"),
    path("newmeter/<str:site_id>", view=meter.meter_create_view, name="meter_create"),
    path(
        "meter_rate_plan/<str:rate_plan_id>",
        view=meter.meter_rate_plan_detail_view,
        name="meter_rate_plan_detail",
    ),
    path(
        "meter_rate_plan_history/<path:meter_id>",
        view=meter.meter_rate_plan_history_view,
        name="meter_rate_plan_history",
    ),
    path("meter/edit/<path:meter_id>", view=meter.meter_edit_view, name="meter_edit"),
    path(
        "meter/deactivate/<path:meter_id>",
        view=meter.meter_deactivate_view,
        name="meter_deactivate",
    ),
    path(
        "meter/view/<path:meter_id>", view=meter.meter_detail_view, name="meter_detail"
    ),
    path("meter/json/<str:meter>", view=meter.meter_data_json, name="meter_data_json"),
    path(
        "meter/<str:meter>/financial_values_table",
        view=meter.meter_financial_values_table,
        name="meter_financial_values_table",
    ),
    path(
        "meter/<str:meter>/financial_values/<str:meter_value_id>",
        view=meter.meter_financial_value_detail,
        name="meter_financial_value_detail",
    ),
    path(
        "meter/<str:meter>/transactions_table",
        view=transaction.meter_transactions_table,
        name="meter_transactions_table",
    ),
    path(
        "meter_financial_value_items_table/<str:meter_value_id>",
        view=meter.meter_financial_value_items_table,
        name="meter_financial_value_items_table",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>",
        view=meter_model_detail_view,
        name="meter_model_detail",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>/details",
        view=meter_model_extra_detail_view,
        name="meter_model_extra_detail",
    ),
    path(
        "meter/<str:meter_id>/create/model",
        view=meter_model_create_view,
        name="meter_model_create",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>/delete",
        view=meter_model_delete_view,
        name="meter_model_delete",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>/delete_production",
        view=meter_model_production_delete_view,
        name="meter_model_production_delete",
    ),
    path(
        "meter/<str:meter_id>/model/<str:id>/calc_saving",
        view=meter_model_calc_saving_view,
        name="meter_model_calc_saving",
    ),
    path("newmodel/", view=model.model_create_view, name="model_create"),
    path(
        "newmodel/<path:entity_id>",
        view=model.model_create_view,

opentaps_seas/users/urls.py
from django.urls import path

from opentaps_seas.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

opentaps_seas/volttron/urls.py
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.

from django.urls import path

from .views import (
    status_view,
    agent_view,
    start_agent,
    stop_agent,
    delete_agent_config,
    store_agent_config
)

app_name = "volttron"
urlpatterns = [
    path("", view=status_view, name="default"),
    path("status", view=status_view, name="status"),
    path("agents/<str:platform>/<str:agent>/view", view=agent_view, name="agent_view"),
    path("agents/<str:platform>/<str:agent>/start", view=start_agent, name="start_agent"),
    path("agents/<str:platform>/<str:agent>/stop", view=stop_agent, name="stop_agent"),
    path("agents/<str:platform>/<str:agent>/delete_config", view=delete_agent_config, name="delete_agent_config"),
    path("agents/<str:platform>/<str:agent>/store_config", view=store_agent_config, name="store_agent_config")
]

opentaps_seas/core/forms/hyperledger.py
from django import forms


class HyperLedgerQueryAdminForm(forms.Form):
    name = forms.CharField(label="Org Name:")

    class Meta:
        fields = ["name"]


class HyperLedgerEnrollUserForm(forms.Form):
    affiliation = forms.CharField()

    class Meta:
        fields = ["affiliation"]

opentaps_seas/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

opentaps_seas/templates/volttron/agent_view.html
{% extends "base.html" %}
{% comment 'header' %}
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% load static i18n %}
{% block title %}VOLTTRON{% endblock %}

{% block content %}
{% load bootstrap4 %}
<div class="container">

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'volttron:status' %}">VOLTTRON</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ agent.name|default:agent_uuid }}</li>
    </ol>
  </nav>

  <div class="card mb-3">
    <div class="card-body">
      {% if volttron_vc_configuration_needed %}
        <p>VOLTTRON has not been configured.</p>
      {% endif %}
      {% if volttron_vc_error %}
        <div class="alert alert-danger" role="alert">
          The following error occurred: {{ volttron_vc_error }}
        </div>
      {% endif %}

      {% if agent %}
        <h2>{{ agent.name }}</h2>
        <hr/>
        <p><b>Identity:</b> {{ agent.identity }}</p>
        <p><b>UUID:</b> {{ agent.uuid }}</p>
        <p><b>Tag:</b> {{ agent.tag }}</p>
        <p><b>Running:</b> {{ agent.is_running }}</p>
        <p><b>Process:</b> {{ agent.process_id }}</p>
        <p><b>Priority:</b> {{ agent.priority }}</p>
        <p><b>Health:</b> {{ agent.health.status }} last updated {{ agent.health.last_updated }}, context {{ agent.health.context }}</p>
        <p><b>Error Code:</b> {{ agent.error_code }}</p>
        <br/>

        <h3>Configuration</h3>
        {% for config in agent_configs %}
          <p>
            <hr/>
            <div class="d-flex">
              <b>{{ config.key }}</b>
              <div class="ml-auto">
                <form method="POST" action="{% url 'volttron:delete_agent_config' platform_uuid agent_uuid %}">
                  {% csrf_token %}
                  <input type="hidden" name="config_name" value="{{config.key}}"/>
                  {% bootstrap_button '<i class="fa fa-trash"></i> Delete' button_class='btn-danger' button_type='submit' %}
                </form>
              </div>
            </div>
            <div>{{ config.value|linebreaks }}</div>
          </p>
        {% endfor %}
        <hr/>
        <h3>Add a new Configuration</h3>
        <form method="POST" action="{% url 'volttron:store_agent_config' platform_uuid agent_uuid %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="config_name">Config Key</label>
            <input type="text" required="required" class="form-control" name="config_name" id="config_name" placeholder="Enter the configuration key">
          </div>
          <div class="form-group">
            <label for="config_type">Config Content Type</label>
            <select id="config_type" name="config_type" required="required" class="form-control">
              <option value="json">JSON</option>
              <option value="csv">CSV</option>
            </select>
          </div>
          <div class="form-group">
            <label for="raw_contents">Config Content (optional)</label>
            <textarea class="form-control" name="raw_contents" id="raw_contents" placeholder="Configuration content"></textarea>
          </div>
          {% bootstrap_button '<i class="fa fa-plus"></i> Add' button_class='btn-primary' button_type='submit' %}
        </form>
      {% else %}
        <p>Agent not found.</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

opentaps_seas/templates/volttron/status.html
{% extends "base.html" %}
{% comment 'header' %}
# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% load static i18n %}
{% block title %}VOLTTRON{% endblock %}

{% block content %}
{% load bootstrap4 %}
<div class="container">

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">VOLTTRON</li>
    </ol>
  </nav>

  <div class="card mb-3">
    <div class="card-body">
      {% if volttron_vc_configuration_needed %}
        <p>No VOLTTRON configuration found.  Please configure IP address, username, and password for accessing VOLTTRON Central.</p>
      {% endif %}
      {% if volttron_vc_error %}
        <div class="alert alert-danger" role="alert">
          The following error occurred: {{ volttron_vc_error }}
        </div>
      {% endif %}
      {% if platforms %}
        {% for platform in platforms %}
          <h3 class="d-flex">{{ platform.name }}
          {% if platform.health %}
           <div class="ml-auto">Status: {{ platform.health.status }}</div>
          {% endif %}
          </h3>
          <div class="text-muted mb-4">{{ platform.uuid }}</div>
          <table class="table">
            <tr>
              <th>Name</th>
              <th>Identity</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
            {% for agent in platform.agents %}
              <tr>
                <td>{{ agent.name }} <div class="text-muted">{{ agent.uuid }}</div></td>
                <td>{{ agent.identity }}</td>
                <td>
                  {% if agent.health %}
                    <div>{{ agent.health.status }}</div>
                  {% else %}
                    <div>N/A</div>
                  {% endif %}
                </td>
                <td>
                  <div class="d-flex">
                    {% if agent.permissions.can_start and not agent.is_running %}
                      <form method="POST" action="{% url 'volttron:start_agent' platform.uuid agent.uuid %}">
                        {% csrf_token %}
                        {% bootstrap_button '<i class="fa fa-play"></i> Start' button_class='btn-primary' button_type='submit' %}
                      </form>
                    {% endif %}
                    {% if agent.permissions.can_stop and agent.is_running %}
                      <form method="POST" action="{% url 'volttron:stop_agent' platform.uuid agent.uuid %}">
                        {% csrf_token %}
                        {% bootstrap_button '<i class="fa fa-stop"></i> Stop' button_class='btn-danger' button_type='submit' %}
                      </form>
                    {% endif %}

                    {% if agent.permissions.can_start and agent.permissions.can_stop %}
                      {% url 'volttron:agent_view' platform.uuid agent.uuid as agent_view_url %}
                      {% bootstrap_button '<i class="fa fa-cog"></i> Configure' button_class='btn-secondary ml-2' href=agent_view_url %}
                    {% endif %}
                  </div>
                </td>
              </tr>
            {% endfor %}
          </table>
        {% endfor %}
      {% else %}
        <p>No running VOLTTRON platforms found.  Please make sure that VOLTTRON is running at the configured IP address and port, and both the volttron central and volttron central platform agents are running.</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}